sm:
  image: shonnahum/sm
  tag: v2.0.0
  port: 5050
  mongo:
    uri: "mongodb://shon:123@172.26.255.104:27017/"
    database: "status"
    collection: "items"
  loki:
    url: "http://172.26.255.104:3100/loki/api/v1/push"
  jaeger:
    host: "localhost"  
    port: 4317

smc:
  image: shonnahum/smc
  tag: v2.0.0
  port: 5051
  backend_api_url: "http://sm.local/store"
  loki:
    url: "http://172.26.255.104:3100/loki/api/v1/push"
  jaeger:
    host: "localhost" 
    port: 4317
