sm:
  image: shonnahum/sm:11
  tag: 1
  port: 5050
  mongo:
    uri: "mongodb://shon:123@172.26.255.104:27017/"
    database: "status"
    collection: "items"

smc:
  image: shonnahum/smc:11
  tag: 1
  port: 5051
  backend_api_url: "http://sm.local/store"
