sm:
  image: shonnahum/sm
  tag: v0.0.0
  port: 5050
  mongo:
    uri: "mongodb://shon:123@172.26.255.104:27017/"
    database: "status"
    collection: "items"

smc:
  image: shonnahum/smc
  tag: v0.0.0
  port: 5051
  backend_api_url: "http://sm.local/store"
