apiVersion: v1
kind: ConfigMap
metadata:
  name: sm-env-configmap
data:
  env.yaml: |-
    mongodb:
      uri: {{ .Values.sm.mongo.uri | quote }}
      database: {{ .Values.sm.mongo.database | quote }}
      collection: {{ .Values.sm.mongo.collection | quote }}
    server:
      port: {{ .Values.sm.port | quote }}
    loki:
      url: {{ .Values.sm.loki.url | quote }}
    jaeger:
      host: {{ .Values.sm.jaeger.host | quote }}
      port: {{ .Values.sm.jaeger.port | quote }}