apiVersion: v1
kind: Service
metadata:
  name: sm-service
spec:
  selector:
    app: sm
  ports:
    - protocol: TCP
      port: {{ .Values.sm.port }}
      targetPort: {{ .Values.sm.port }}
  type: ClusterIP
