apiVersion: v1
kind: Service
metadata:
  name: smc-service
spec:
  selector:
    app: smc
  ports:
    - protocol: TCP
      port: {{ .Values.smc.port }}
      targetPort: {{ .Values.smc.port }}
  type: ClusterIP
